services:
  app:
    build:
      context: ./backend
      dockerfile: ${FM_DOCKER_FILE}
    ports:
      - "1323:1323"
    volumes:
      - ./backend:/app
    environment:
      - GO111MODULE=on
      - API_KEY=${FM_API_KEY}
      - PRAYER_BASEURL=${FM_PRAYER_BASEURL}
      - WEATHER_BASEURL=${FM_WEATHER_BASEURL}
      - WEATHER_API_KEY=${FM_WEATHER_API_KEY}
      - ALLOWED_ORIGIN=${FM_ALLOWED_ORIGIN}
    command: air -c .air.toml
