services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "1323:1323"
    volumes:
      - ./backend:/app
    environment:
      - GO111MODULE=on
      - API_KEY=PASTE_API_KEY
    command: air -c .air.toml
