# Use official Golang image
FROM golang:1.24

# Set working directory
WORKDIR /app

# Install Air for live reload
RUN go install github.com/air-verse/air@latest

# Copy go.mod and go.sum for dependency management
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the application source code
COPY . .

# Expose the application port
EXPOSE 1323

# Start the app using Air for live-reload
# CMD ["air", "-c", ".air.toml"]
